trigger:
    branches:
        include:
        - master

pool:
  vmImage: 'windows-2019'

variables:
  CI: True

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'  # does not matter too much, because we are creating a conda env below
    architecture: 'x64'  # 64-bit windows
  displayName: 'Set Python version'

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH

- script: |
    conda install conda=4.6.14 --yes
    conda env create --quiet --file=environment.yml --name=testEnv
    call activate testEnv
    pip install -e .
  displayName: Setup python environment

- script: |
    call activate testEnv
    pytest --cov=./sp_experiment --cov-report=xml --verbose
  displayName: Testing and coverage via pytest --cov

- script: |
    call activate testEnv
    flake8 .
  displayName: Linting via flake8

- bash: bash <(curl -s https://codecov.io/bash) -t 632f0304-5f76-4a28-8a46-43d16438eb27
  displayName: Upload coverage to codecov.io
