name: sp_experiment
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- numpy
- scipy
- matplotlib
- pandas
- wxpython
- pip:
  - pyopengl
  - pyglet
  - pillow
  - moviepy
  - lxml
  - openpyxl
  - configobj
  - psychopy==3.0.4
  - pytest  # testing
  - pytest-cov  # testing
  - flake8  # linter
  - flake8-docstrings  # linter
