
name: sp_experiment
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- numpy
- scipy
- matplotlib
- pandas
- wxpython
- pip:
  - pyopengl
  - pyglet
  - pillow
  - moviepy
  - lxml
  - openpyxl
  - configobj
  - psychopy==3.0.4
  - pytest
  - pytest-cov
