name: sp_experiment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - pip<10  # XXX to be fixed
  - cython
  - numpy
  - scipy
  - matplotlib
  - pandas
  - wxpython
  - pyopengl
  - pyglet
  - pillow
  - moviepy
  - lxml
  - openpyxl
  - configobj
  - pytest  # testing
  - pytest-cov  # testing
  - flake8  # linter
  - flake8-docstrings  # linter
  - pip:
    - PyPubSub
    - psychopy==3.0.7
