name: sp_experiment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip=19
  - cython
  - numpy
  - scipy
  - matplotlib
  - pandas
  - wxpython
  - pyopengl
  - pyglet
  - pillow
  - moviepy
  - lxml
  - openpyxl
  - configobj
  - pytest  # testing
  - pytest-cov  # testing
  - flake8  # linter
  - flake8-docstrings  # linter
  - pip:
    - psychopy==3.0
    - tobii-research
    - pytest-sugar
    - pytest-faulthandler
