version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.8-jessie
        steps:
            - checkout
            - run:
                name: Update for tobii-research python module
                command: |
                  sudo apt-get update
                  sudo apt-get upgrade
                  export LD_LIBRARY_PATH=/usr/local/lib
            - run:
                name: Install miniconda
                command: |
                  wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh;
                  chmod +x ~/miniconda.sh;
                  ~/miniconda.sh -b -p ~/miniconda;
                  echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
            - run:
                name: Setup Python environment
                command: |
                  conda update --yes --quiet conda
                  conda env create -f environment.yml
                  source activate sp_experiment
                  python setup.py develop
            - run:
                name: Run the tests and upload coverage
                command: |
                    source activate sp_experiment
                    make test
                    bash <(curl -s https://codecov.io/bash)
