name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        python-version: [3.6]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sp_experiment
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Check formatting
      shell: bash -l {0}
      if: "matrix.platform == 'windows-latest'"
      run: |
        flake8 .

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --cov=./sp_experiment --cov-report=xml --verbose

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
